
[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
style = "bold red"
threshold = 30

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
discharging_symbol = "ğŸ’¦"
style = "bold yellow"
threshold = 50

[[battery.display]]
style = "green"
threshold = 100

[battery]
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ“‰ "
empty_symbol = "ğŸ’€ "
full_symbol = "ğŸ”‹ "

[time]
style = "cyan"
disabled = false

[status]
disabled = false
format = 'âœ—[$symbol $common_meaning$signal_name$maybe_int]âœ—($style) '
map_symbol = true


[git_branch]
style = "bold cyan"